### ISSUE TITLE
"Handling the RFC command failed :("

### ISSUE THREAD

**Issue by tomaka** [paritytech/rfc-action#19]
See https://github.com/polkadot-fellows/RFCs/pull/8#issuecomment-1763848583

As instructed, I'm opening an issue.

**Comment by rzadp** [comment]
Thanks for the report.

There hasn't been any changes since the last time [it worked](https://github.com/polkadot-fellows/RFCs/pull/7#issuecomment-1717730755).
The error log suggests a permissions issue.
It's not clear but I suspect that it's a setting preventing first time contributors from running workflows. You are in fact opening a first PR in that particular repo, whereas the previous time it worked the author was already a contributor at that time.

I'll try to confirm this guess and think about what we can do with it.

**Comment by rzadp** [comment]
Update: this is NOT a first-time-contributor thing as I initially thought.

It's still seems to be a permissions issue but I don't know what's missing (nothing's been changed on my side, and it continues to work in a testing org/repo).

**Comment by rzadp** [comment]
The issue has been fixed and the PR is not merged: https://github.com/polkadot-fellows/RFCs/pull/8#issuecomment-1777113262

I have tried maany things and it's still not known what was the exact cause of this problem, all we know is that merging was denied by github on this particular PR.

The issue has been resolved by changing the merging code from using github's REST API to graphl API.
