### ISSUE TITLE
Handling the RFC command failed

### ISSUE THREAD

**Issue by skunert** [paritytech/rfc-action#32]
I tried to merge an RFC, however the command failed.
https://github.com/polkadot-fellows/RFCs/pull/43#issuecomment-1924206809

Block hash `0x6386c7812bbed74cde165d0a074e69fa1b5d6845bf8aa914276305baf6f3b240` looks correct  to me however and contains the confirmed event: https://collectives.statescan.io/#/blocks/0x6386c7812bbed74cde165d0a074e69fa1b5d6845bf8aa914276305baf6f3b240

**Comment by rzadp** [comment]
Hey @skunert,

It looks like the referendum passed, but failed to execute upon enactment:

![Screenshot 2024-02-02 at 18 54 23](https://github.com/paritytech/rfc-action/assets/12039224/7a80c1b9-e075-44a7-ae2c-a2bbbdaed507)

That's why the command fails to process the PR.

As to why the referendum didn't execute, I don't know, have to look into it.

**Comment by skunert** [comment]
I think this was some runtime bug at that time. All referenda at that time showed this failure.

The logs of the action that is linked in the issue indicate that it could not fetch the header for whatever reason.

**Comment by rzadp** [comment]
I've run `/rfc propose` again and the bot generates a proper `Fellows` origin.

**Comment by rzadp** [comment]
@skunert Is it possible that you first generated the link which encoded the "second origin", then the release happened, and then you used the link to generate the referendum?

**Comment by skunert** [comment]
Possible, there was some time between the link generation and me opening the referendum.
